### ISSUE TITLE
MSVC_BASE and Windows SDK

### ISSUE THREAD

**Issue by cryptocub3** [ProdriveTechnologies/msvc-sdk-for-non-windows-hosts#2]
Can you provide instructions how we can obtain them on Linux systems ? Wonderful project

**Comment by royvandam** [comment]
Hi there, thanks for the interest!

We took the files from a licensed copy of Visual Studio 2017 on Windows 10.

The files are located in following places:
- C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC
- C:\Program Files (x86)\Windows Kits\10

Hence I am not entirely sure where to find the MSVC SDK files for C/C++ to be honest. I assume these files are also part of the [free community edition](https://visualstudio.microsoft.com/vs/community/) of Visual Studio as it supports development for C++. Just be sure to install the following packages from the `Individual components` tab of the installer:

- VC++ 2017 version 15.7 v14.14 latest v141 tools

I hope this helps, please let me know if this works out for you!
